package edu.utexas.cs.cs378.week2;

import edu.utexas.cs.cs378.TripData;
import lombok.AllArgsConstructor;
import lombok.Data;

// generated by map service

// memory usage
//   carHashMd5         16
//   driverHashMd5      16
//   total               2  (ushort; max 50000 > Short.MAX_VALUE)
//   ----------------------------------
//   total              34 bytes/record
//
@Data
@AllArgsConstructor
public class TripDriverCarTotalData {
    byte[] carHash;
    byte[] driverHash;
    // same thing as before, we serialize this as ushort.
    int total;

    public TripDriverCarTotalData(TripData data) {
        this(data.getCarHash(), data.getDriverHash(), data.getTotal());
    }
}
